listen_address  = "127.0.0.1:9003"
control_address = "127.0.0.1:9004"

[node]
proxy_address   = "http://127.0.0.1:9003"
control_address = "http://127.0.0.1:9004"
peer_address    = "https://127.0.0.1:9444"

[endpoint_tls]
cert_path           = "certs/runtime-proxy-endpoint/leaf.pem"
key_path            = "certs/runtime-proxy-endpoint/key.pem"
client_ca_cert_path = "certs/runtime-client-root/ca.crt"

[client_tls]
cert_path           = "certs/runtime-proxy-client/leaf.pem"
key_path            = "certs/runtime-proxy-client/key.pem"
server_ca_cert_path = "certs/runtime-server-root/ca.crt"

[database]
url                             = "postgres://postgres@localhost:5433/wruntime_example"
manager_liveness_threshold_secs = 5

[cache]
routing_table_ttl_secs = 5
