metadata_dir = "/data/meta"
data_dir     = "/data/store"
db_engine    = "sqlite"

replication_factor = 1

[rpc_bind_addr]
type = "tcp"
addr = "0.0.0.0:3910"

[rpc_public_addr]
type = "tcp"
addr = "127.0.0.1:3910"

[s3_api]
s3_region     = "garage"
api_bind_addr = "0.0.0.0:3900"

[admin]
api_bind_addr = "0.0.0.0:3901"
