syntax = "proto3";
package test;

service HttpTestService {
  rpc Egress (EgressRequest) returns (EgressResponse);
  rpc GetUrl (GetUrlRequest) returns (GetUrlResponse);
  rpc Echo   (EchoRequest)   returns (EchoResponse);
}

message EgressRequest {
  string authority = 1;
  string path      = 2;
  bytes  body      = 3;
}
message EgressResponse {
  uint32 status = 1;
  string body   = 2;
}

message GetUrlRequest {
  string url = 1;
}
message GetUrlResponse {
  uint32 status = 1;
  bytes body = 2;
}

message EchoRequest {
  string message = 1;
}
message EchoResponse {
  string message = 1;
}
