listen_address = "0.0.0.0:9200"

[node]
proxy_address   = "http://127.0.0.1:9001"
control_address = "http://127.0.0.1:9002"

[[module]]
name                 = "simulator"
namespace            = "stockmarket"
version              = "1.0.0"
wasm_path            = "examples/stockmarket/simulator/target/wasm32-wasip2/release/simulator.wasm"
schema_path          = "examples/stockmarket/schemas/simulator.binpb"
request_timeout_secs = 240
