listen_address = "127.0.0.1:9200"

[node]
proxy_address   = "http://127.0.0.1:9001"
control_address = "http://127.0.0.1:9002"
peer_port       = 9443

[node.tls]
cert_path    = "certs/127.0.0.1.crt"
key_path     = "certs/127.0.0.1.key"
ca_cert_path = "certs/ca.crt"

[[module]]
name                 = "simulator"
namespace            = "stockmarket"
version              = "1.0.0"
wasm_path            = "examples/stockmarket/simulator/target/wasm32-wasip2/debug/simulator.wasm"
schema_path          = "examples/stockmarket/schemas/simulator.binpb"
request_timeout_secs = 240
