listen_address = "0.0.0.0:9101"

[node]
proxy_address   = "http://127.0.0.1:9001"
control_address = "http://127.0.0.1:9002"

# [[module]]
# name        = "my-service"
# namespace   = "my-ns"
# version     = "1.0.0"
# wasm_path   = "path/to/module.wasm"
# schema_path = "path/to/schema.binpb"
