package codegen:collector@1.0.0;

world collector {
  import wruntime:blobstore/store@0.1.0;
  import wruntime:tracing/span@0.1.0;
  import wasi:cli/stderr@0.2.6;
  import wasi:cli/environment@0.2.6;
  import wasi:cli/exit@0.2.6;
  import wasi:http/types@0.2.6;
  import wasi:http/outgoing-handler@0.2.6;
  import wasi:io/streams@0.2.6;
  import wasi:io/poll@0.2.6;
  import wasi:io/error@0.2.6;
  import wasi:clocks/monotonic-clock@0.2.6;
  import wasi:random/random@0.2.6;
  export wasi:http/incoming-handler@0.2.6;
}
